export enum TaskActionTypes {
    ADD_TASK_ENTRY = "ADD_TASK_ENTRY",
    UPDATE_TASK_STATE = "UPDATE_TASK_STATE",
    GET_TASK_ENTRIES = "GET_TASK_ENTRIES",
    DELETE_TASK_ENTRY = "DELETE_TASK_ENTRY"
}
