export enum TodoActionTypes {
    ADD_TODO_ENTRY = "ADD_TODO_ENTRY",
    UPDATE_TODO_STATE = "UPDATE_TODO_STATE",
    GET_TODO_ENTRIES = "GET_TODO_ENTRIES",
    DELETE_TODO_ENTRY = "DELETE_TODO_ENTRY",
    UPDATE_TODO_ASSIGNEE = "UPDATE_TODO_ASSIGNEE"
}
