version: '3.7'

services:
  todo-react-frontend:
    image: ghcr.io/deanagan/crud-stacks/todo-react-frontend:latest
    ports:
      - 3001:3000
  todo-aspdotnet-backend:
    image: ghcr.io/deanagan/crud-stacks/todo-aspdotnet-backend:latest
    restart: unless-stopped
    ports:
      - 8090:80
    entrypoint: ["/app/wait-for-it.sh", "database:14331", "-t", "120", "--", "dotnet", "TodoBackend.Api.dll"]
    depends_on:
      - database
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      SA_PASSWORD: "1Secure*Password1"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - ./sqlvolume/data:/var/opt/mssql/data
      - ./sqlvolume/log:/var/opt/mssql/log
      - ./sqlvolume/secrets:/var/opt/mssql/secrets
    ports:
    - "14331:1433"
