# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  todobackendapi:
    image: todobackendapi
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    build:
      context: .
      dockerfile: TodoBackend.Api/Dockerfile
    ports:
      - 8090:5000
    depends_on:
      - database
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      SA_PASSWORD: "1Secure*Password1"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - ./sqlvolume/data:/var/opt/mssql/data
      - ./sqlvolume/log:/var/opt/mssql/log
      - ./sqlvolume/secrets:/var/opt/mssql/secrets
    ports:
    - 14331:1433