version: '3.7'

services:
  react-frontend:
    container_name: todo-react-frontend
    build:
      context: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true